import type { Metadata } from "next";
import { Noto_Sans_Thai, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from '@/app/components/ReduxProvider'

const noto = Noto_Sans_Thai({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Web Application Platfrom for Programming Classroom",
  description: "Generated by create next app",
  icons: {
    icon: ['/favicon.ico?v=4']
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
